Configuration:
  status: debug
  Appends:
    Console:
      name: Console
      target: SYSTEM_OUT
      Layout:
        PatternLayout:
          pattern: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  Loggers:
    Root:
      level: warn
      AppenderRef:
        ref: Console
    Logger:
      - name: io.netty
        level: warn
        AppenderRef:
          ref: Console
